"""Agent system for multi-agent spreadsheet analysis.

This package provides a functional multi-agent architecture for
analyzing spreadsheets, with specialized agents for different tasks.
"""

from .communication import (
    CapabilityRouter,
    DirectRouter,
    MessageBus,
    RoundRobinRouter,
    chain_of_responsibility,
    create_capability_router,
    create_message_bus,
    request_response,
    scatter_gather,
)
from .coordination import (
    CoordinationStrategy,
    Coordinator,
    HierarchicalStrategy,
    MapReduceStrategy,
    ParallelStrategy,
    SequentialStrategy,
    create_coordinator,
    create_map_reduce_coordinator,
)
from .core import (
    CompositeAgent,
    FunctionalAgent,
    StatefulAgent,
    create_composite_agent,
    create_echo_agent,
    create_filter_agent,
    create_pipeline_agent,
    create_simple_agent,
    create_transform_agent,
)
from .spreadsheet_agents import (
    create_context_optimizer,
    create_data_validator,
    create_formula_analyzer,
    create_pattern_detector,
    create_spreadsheet_analysis_team,
    create_summary_generator,
)
from .types import (
    Agent,
    AgentCapability,
    AgentId,
    AgentMemory,
    AgentMessage,
    AgentResponse,
    AgentState,
    CoordinationPlan,
    CoordinationStep,
    MessageRouter,
    Task,
    TaskResult,
)

__all__ = [
    "Agent",
    "AgentCapability",
    "AgentId",
    "AgentMemory",
    "AgentMessage",
    "AgentResponse",
    "AgentState",
    "CapabilityRouter",
    "CompositeAgent",
    "CoordinationPlan",
    "CoordinationStep",
    "CoordinationStrategy",
    "Coordinator",
    "DirectRouter",
    "FunctionalAgent",
    "HierarchicalStrategy",
    "MapReduceStrategy",
    "MessageBus",
    "MessageRouter",
    "ParallelStrategy",
    "RoundRobinRouter",
    "SequentialStrategy",
    "StatefulAgent",
    "Task",
    "TaskResult",
    "chain_of_responsibility",
    "create_capability_router",
    "create_composite_agent",
    "create_context_optimizer",
    "create_coordinator",
    "create_data_validator",
    "create_echo_agent",
    "create_filter_agent",
    "create_formula_analyzer",
    "create_map_reduce_coordinator",
    "create_message_bus",
    "create_pattern_detector",
    "create_pipeline_agent",
    "create_simple_agent",
    "create_spreadsheet_analysis_team",
    "create_summary_generator",
    "create_transform_agent",
    "request_response",
    "scatter_gather",
]
