services:
  neo4j:
    image: neo4j:5.25.1
    container_name: spreadsheet-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      # Authentication
      - NEO4J_AUTH=neo4j/spreadsheet123

      # Memory settings
      - NEO4J_server_memory_pagecache_size=1G
      - NEO4J_server_memory_heap_initial__size=512M
      - NEO4J_server_memory_heap_max__size=1G

      # Enable APOC procedures
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4JLABS_PLUGINS=["apoc"]

    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    healthcheck:
      test: ["CMD", "neo4j", "status"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 40s

  # Python application for loading spreadsheets
  spreadsheet-loader:
    build:
      context: .
      dockerfile: docker/Dockerfile.loader
    container_name: spreadsheet-loader
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=spreadsheet123
      - PYTHONUNBUFFERED=1
    volumes:
      - ./src:/app/src
      - ./test-files:/app/test-files
      - ./logs:/app/logs
    command: python -m spreadsheet_analyzer.graph_db.batch_loader

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local
